* Hl-line-fringe                                                   :noexport:

[[https://travis-ci.org/hubisan/hl-line-fringe][https://travis-ci.org/hubisan/hl-line-fringe.svg?branch=master]] 
[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg]]

**Pre-release version, don't use this.**

-----

Highlight current line and/or indicate the current line in the fringe locally or
globally.

** Main features

- Highlight the current line
- * Indicate the current line in the fringe
- * Different faces in current and inactive buffers
- * Different fringe indicator bitmaps in current and inactive buffers
- * If the same buffer is shown in multiple windows the sticky overlays are handled as expected
  
\star not available with hl-line-mode

-----

* Contents                                                        :TOC:QUOTE:
#+BEGIN_QUOTE
- [[#usage][Usage]]
  - [[#customization][Customization]]
  - [[#faces][Faces]]
- [[#installation][Installation]]
- [[#changelog][Changelog]]
- [[#contributing][Contributing]]
#+END_QUOTE

* Usage

Turn the mode on in a buffer with ~(hl-line-fringe-mode)~ or globally with ~(global-hl-line-fringe-mode)~.

** Customization

Set the following variables to change the behaviour of the mode (default values in parens):

- ~hl-line-fringe-line~ :: (t) If non-nil highlighting the line is enabled.
- ~hl-line-fringe-line-sticky~ :: If nil the line hightlight is only shown in the current buffer.
- ~hl-line-fringe-line-overlay-priority~ :: (-50) Priority of line highlight overlay. 
- ~hl-line-fringe-indicator~ :: (t) If non-nil the fringe indicator is enabled.
- ~hl-line-fringe-indicator-char~ :: ("X") Character used to draw the indicator on character terminals.
- ~hl-line-fringe-indicator-bitmap~ :: ('hl-line-fringe-indicator-bitmap-1) Fringe bitmap to use for the indicator.
- ~hl-line-fringe-indicator-bitmap-inactive~ :: ('hl-line-fringe-indicator-bitmap-2) Fringe bitmap to use for the indicator if buffer is inactive. 
- ~hl-line-fringe-indicator-sticky~ :: (t) If nil the fringe indicator is only shown in the current buffer.
- ~hl-line-fringe-indicator-overlay-priority~ :: (1) Priority of fringe indicator overlay.
- ~hl-line-fringe-global-ignored-major-modes~ :: (nil) List of major modes to ignore with global mode.

** Faces

The following faces are defined:

- ~hl-line-fringe-line~ :: Face used to highlight the current line if buffer is active.
- ~hl-line-fringe-line-inactive~ :: Face used to highlight the current line if buffer is inactive.
- ~hl-line-fringe-indicator~ :: Face used to indicate the current line in the fringe if buffer is active.
- ~hl-line-fringe-indicator-inactive~ :: Face used to indicate the current line in the fringe if buffer is inactive.
    
* Installation

Install the ivy package from MELPA.

With [[https://github.com/jwiegley/use-package][use-package]]:

#+BEGIN_SRC emacs-lisp
  (use-package hl-line-fringe-mode
    :ensure nil
    :defer t
    :hook (after-init . global-hl-line-fringe-mode)
    :init
    ;; Customization
    (setq
     hl-line-fringe-line t
     hl-line-fringe-indicator t
     hl-line-fringe-line-sticky t
     hl-line-fringe-indicator-sticky t
     hl-line-fringe-indicator-bitmap 'hl-line-fringe-indicator-bitmap-1
     hl-line-fringe-indicator-bitmap-inactive 'hl-line-fringe-indicator-bitmap-2
     ;; ...
     )
    :custom-face
    (hl-line-fringe-line ((t (:inherit highlight))))
    (hl-line-fringe-line-inactive ((t (:inherit lazy-highlight))))
    (hl-line-fringe-indicator ((t (:inherit font-lock-keyword-face))))
    (hl-line-fringe-indicator-inactive ((t (:inherit font-lock-comment-face)))))
#+END_SRC

* Changelog

** 0.1.0                                                           :noexport:

First version on github, still very alpha.

* Contributing

Install dependencies for testing with ~cask install~.

Before submitting a change run ~make~ to:

 - run the tests,
 - checkdoc,
 - package-lint 
 - and elisp-lint.
   
* Remarks                                                          :noexport:

Using two overlays instead of one to be able to use another priority for the
fringe indicator. Without that the fringe indicator could be just added to the
other overlay as 'before-string property. But this would hide the indicator
behind many other fringe bitmaps.
